In [4]:
#installing pandas
!  pip install pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: pandas in C:\Users\lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (3.0.2)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (from pandas) (2.4.4)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in C:\Users\lenovo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [5]:
#import pandas 
import pandas as pd

In [5]:
#checking  pandas version 
print(pd.__version__)

3.0.0

In [15]:
# 1.creating dataframe 
df =pd.DataFrame([11,22,33])
print(df)

    0
0  11
1  22
2  33

In [8]:
#giving column name in dataframe 
df =pd.DataFrame([11,22,33],columns = ['col_name'])
print(df)

   col_name
0        11
1        22
2        33

In [9]:
print(type(df))

<class 'pandas.DataFrame'>

In [6]:
#take a hashmap data 
#in it key treated as column name and others are data 
data = {
    "name" : ["rahul " ,"raj ", "rajeev ","priya "],
    "age " : [22,23,34,26],
    "salary " : [200000,100000,50000,45000]
}
ddf =pd.DataFrame(data)
print(ddf)

      name  age   salary
0   rahul     22   200000
1     raj     23   100000
2  rajeev     34    50000
3   priya     26    45000

In [20]:
print(type(ddf))

<class 'pandas.DataFrame'>

In [21]:
#2. basic dataframe understanding

In [24]:
ddf.head()# it give us top rows and its by dafault value is 5 thats why it gives all data

      name  age   salary
0   rahul     22   200000
1     raj     23   100000
2  rajeev     34    50000
3   priya     26    45000

In [7]:
ddf.tail(2) #for give last elements and it is also by deafult 5

      name  age   salary
2  rajeev     34    50000
3   priya     26    45000

In [8]:
ddf.shape # find total number of rows and colums

(4, 3)

In [36]:
ddf.columns # it gives all the columns name

Index(['name', 'age ', 'salary '], dtype='str')

In [14]:
#rename 
df1 = ddf.rename(columns = {"salary " : "monthly_salary"})

In [40]:
df1

      name  age   monthly_salary
0   rahul     22          200000
1     raj     23          100000
2  rajeev     34           50000
3   priya     26           45000

In [ ]:
df1.info() # tell  information about dataframe

<class 'pandas.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   name            4 non-null      str
 1   age             4 non-null      int64
 2   monthly_salary  4 non-null      int64
dtypes: int64(2), str(1)
memory usage: 228.0 bytes

In [45]:
df1.describe() # it describe statistical summary of data like mean ,minn max

            age   monthly_salary
count   4.000000        4.000000
mean   26.250000    98750.000000
std     5.439056    71922.991224
min    22.000000    45000.000000
25%    22.750000    48750.000000
50%    24.500000    75000.000000
75%    28.000000   125000.000000
max    34.000000   200000.000000

In [12]:
#3.save and load data from csv(commas seperated values ) file .
ddf

      name  age   salary
0   rahul     22   200000
1     raj     23   100000
2  rajeev     34    50000
3   priya     26    45000

In [15]:
df1

      name  age   monthly_salary
0   rahul     22          200000
1     raj     23          100000
2  rajeev     34           50000
3   priya     26           45000

In [19]:
#save data into csv file in a particular location 
df1.to_csv(r'C:\Users\lenovo\Desktop\pandas\test.csv')

In [ ]:
# load csv data from csv file into notebook.
loaded_df = pd.read_csv("test.csv")

In [21]:
loaded_df

   Unnamed: 0     name  age   monthly_salary
0           0   rahul     22          200000
1           1     raj     23          100000
2           2  rajeev     34           55000
3           3   priya     26           45000

In [25]:
#4. rows & column selection 
#column selection 
df1[["name"]]

      name
0   rahul
1     raj
2  rajeev
3   priya

In [27]:
df1[["name" ,"monthly_salary"]] #for selecting your choice column

      name  monthly_salary
0   rahul           200000
1     raj           100000
2  rajeev            50000
3   priya            45000

# we can also filter the values from it

In [32]:
df1

      name  age   monthly_salary
0   rahul     22          200000
1     raj     23          100000
2  rajeev     34           50000
3   priya     26           45000

In [41]:
#for selecting rows by name 
#loc meaning is label based indexing 
df1['name'] = df1['name'].str.strip() # remove the void spaces from it using strip()
df1.loc[df1['name'] == 'rahul']#then using loc function

    name  age   monthly_salary
0  rahul    22          200000

In [40]:
df1.loc[(df1['name'] == 'rahul') & (df1['monthly_salary'] > 150000)]
 # this is basically for printing rahul name persons in list who's salary is higher then 150000 and we using & operator for condition

    name  age   monthly_salary
0  rahul    22          200000

In [43]:
#selecting value via index value 
df1.iloc[1]

name                 raj
age                   23
monthly_salary    100000
Name: 1, dtype: object

In [48]:
#we can also use slicing on it 
df1.iloc[0:2]# iloc does'nt takes 2 row

    name  age   monthly_salary
0  rahul    22          200000
1    raj    23          100000

In [47]:
df1.loc[0:2]# loc method takes 2 row as well

     name  age   monthly_salary
0   rahul    22          200000
1     raj    23          100000
2  rajeev    34           50000

In [52]:
# filter dataframe 
df1['age '] > 24 # it gives boolean value in output

0    False
1    False
2     True
3     True
Name: age , dtype: bool

In [54]:
#if we want actual row which satisfied condition 
df1[df1['age '] >24]

     name  age   monthly_salary
2  rajeev    34           50000
3   priya    26           45000

In [56]:
# we can also store this filter dateframe into new dataframe 
filtered_by_age_df = df1[df1['age '] >24]
filtered_by_age_df

     name  age   monthly_salary
2  rajeev    34           50000
3   priya    26           45000

In [57]:
# we can also filter value on the basic of 2 or more condition 
df1[(df1['age '] > 24)&(df1['monthly_salary'] >48000)]

     name  age   monthly_salary
2  rajeev    34           50000

In [59]:
# if we need to filter value with changing the size of dataframe 
df1.where(df1['age '] > 26) # we use df.where() function

     name  age   monthly_salary
0     NaN   NaN             NaN
1     NaN   NaN             NaN
2  rajeev  34.0         50000.0
3     NaN   NaN             NaN

In [61]:
# we also replace nan with anything 
df1.where(df1['age '] >=26 , other = 'Not Eligible')

           name          age  monthly_salary
0  Not Eligible  Not Eligible   Not Eligible
1  Not Eligible  Not Eligible   Not Eligible
2        rajeev            34          50000
3         priya            26          45000

In [63]:
#6. rows and columns operations (add ,update ,delete )
df1

     name  age   monthly_salary
0   rahul    22          200000
1     raj    23          100000
2  rajeev    34           50000
3   priya    26           45000

In [64]:
#adding new column
df1['Team'] = ['AI-ML EXCUTIVE','HR','SD','SALES']
df1

     name  age   monthly_salary            Team
0   rahul    22          200000  AI-ML EXCUTIVE
1     raj    23          100000              HR
2  rajeev    34           50000              SD
3   priya    26           45000           SALES

In [67]:
#we can also crete a column according to salary mulpication of each employee 
df1['Bonus'] = df1['monthly_salary'] *0.2
df1

     name  age   monthly_salary            Team    Bonus
0   rahul    22          200000  AI-ML EXCUTIVE  40000.0
1     raj    23          100000              HR  20000.0
2  rajeev    34           50000              SD  10000.0
3   priya    26           45000           SALES   9000.0

In [75]:
#we can also uppte salary by 1000 using-- df1['monthly_salary'] = df1['monthly_salary'] + 1000
df1

     name  age   monthly_salary            Team    Bonus
0   rahul    22          201000  AI-ML EXCUTIVE  40000.0
1     raj    23          101000              HR  20000.0
2  rajeev    34           51000              SD  10000.0
3   priya    26           46000           SALES   9000.0

In [77]:
# for adding new row we use loc method 
df1.loc[len(df1)] = ['shivam',30,20000,'IT',4000]
df1

     name  age   monthly_salary            Team    Bonus
0   rahul    22          201000  AI-ML EXCUTIVE  40000.0
1     raj    23          101000              HR  20000.0
2  rajeev    34           51000              SD  10000.0
3   priya    26           46000           SALES   9000.0
4  shivam    30           20000              IT   2000.0
5  shivam    30           20000              IT   4000.0

In [80]:
#for delete a row 
df1 =df1.drop(5)
df1

     name  age   monthly_salary            Team    Bonus
0   rahul    22          201000  AI-ML EXCUTIVE  40000.0
1     raj    23          101000              HR  20000.0
2  rajeev    34           51000              SD  10000.0
3   priya    26           46000           SALES   9000.0

In [82]:
df1.loc[len(df1)] = ['sherya',27,30000,'IT',6000]
df1

     name  age   monthly_salary            Team    Bonus
0   rahul    22          201000  AI-ML EXCUTIVE  40000.0
1     raj    23          101000              HR  20000.0
2  rajeev    34           51000              SD  10000.0
3   priya    26           46000           SALES   9000.0
4  sherya    27           30000              IT   6000.0

In [83]:
len(df1)

5

In [88]:
#update value by index value
df1.loc[0,'monthly_salary'] = 190000
df1
#simple meaning jaha index no - 0 hai waha salary 190000 kardo

     name  age   monthly_salary            Team    Bonus
0   rahul    22          190000  AI-ML EXCUTIVE  40000.0
1     raj    23          101000              HR  20000.0
2  rajeev    34           51000              SD  10000.0
3   priya    26           46000           SALES   9000.0
4  sherya    27           30000              IT   6000.0

In [89]:
#updating value by column values 
df1.loc[df1.name == 'rahul' ,'monthly_salary'] =200000
df1
#simple meaning jaha bhi name = rahul hai waha salary 200000 kardo

     name  age   monthly_salary            Team    Bonus
0   rahul    22          200000  AI-ML EXCUTIVE  40000.0
1     raj    23          101000              HR  20000.0
2  rajeev    34           51000              SD  10000.0
3   priya    26           46000           SALES   9000.0
4  sherya    27           30000              IT   6000.0

In [ ]:
# delete row and column values